name = "flareact-template"
type = "webpack"
account_id = "559a8b5d64ed7c768c0fdc6341fd4fb7"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "node_modules/flareact/webpack"

[site]
bucket = "out"
entry-point = "./"
